version: '3'

services:
    web:
        command: bash -c "python3 manage.py migrate;
                          python3 manage.py runserver 0.0.0.0:8000"
        build: .
        volumes:
            - .:/code
        ports:
            - "80:8000"
