version: '3'

services:
    db:
        image: postgres
    web:
        # Docker hack to wait until Postgres is up, then run stuff.
        # https://www.stavros.io/posts/how-deploy-django-docker/
        command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done;
                          python3 manage.py migrate;
                          while :; do python3 manage.py runserver 0.0.0.0:8000; sleep 1; done"
        build: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
